/**
 * Mock data for UBID Intelligence Platform.
 * Used as fallback when backend is unreachable, so the frontend
 * renders populated pages on first load.
 */

import type {
  SummaryResponse,
  SearchResult,
  QueueResponse,
  QueueItem,
  ReviewCase,
  UbidDetail,
  ActivityEvent,
  QueryResult,
  AuditEntry,
} from "./api";

// ─── Dashboard Summary ──────────────────────────────────────────────
export const MOCK_SUMMARY: SummaryResponse = {
  total_ubids: 2_847,
  total_records: 14_235,
  status_breakdown: {
    active: 1_932,
    dormant: 612,
    closed: 189,
    unclassified: 114,
  },
};

// ─── Search Results ─────────────────────────────────────────────────
export const MOCK_SEARCH_RESULTS: SearchResult[] = [
  {
    ubid: "UBID-KA-2024-00142",
    name: "ABC Textiles Pvt Ltd",
    departments: ["factories", "labour", "kspcb"],
    status: "active",
    confidence: 0.94,
    explanation: "Matched via PAN + normalised name across 3 departments",
  },
  {
    ubid: "UBID-KA-2024-00287",
    name: "Bangalore Steel Works",
    departments: ["factories", "kspcb"],
    status: "active",
    confidence: 0.91,
    explanation: "Matched via GSTIN and address proximity",
  },
  {
    ubid: "UBID-KA-2024-00531",
    name: "Sri Lakshmi Enterprises",
    departments: ["shop_est", "labour"],
    status: "dormant",
    confidence: 0.87,
    explanation: "Name similarity 0.92, phone match confirmed",
  },
  {
    ubid: "UBID-KA-2024-00098",
    name: "Karnataka Chemicals & Fertilizers",
    departments: ["factories", "kspcb", "labour", "bescom"],
    status: "active",
    confidence: 0.96,
    explanation: "Exact PAN and GSTIN match across 4 departments",
  },
  {
    ubid: "UBID-KA-2024-00763",
    name: "Mysore Silk Palace",
    departments: ["shop_est"],
    status: "active",
    confidence: 0.82,
    explanation: "Single department, name normalisation high confidence",
  },
  {
    ubid: "UBID-KA-2024-00415",
    name: "Hubli Engineering Corp",
    departments: ["factories", "labour"],
    status: "closed",
    confidence: 0.89,
    explanation: "Matched via address and phone, closure confirmed by both depts",
  },
];

// ─── Reviewer Queue ─────────────────────────────────────────────────
const MOCK_QUEUE_ITEMS: QueueItem[] = [
  {
    case_id: "CASE-2024-0891",
    name_a: "ABC Textiles Pvt Ltd",
    name_b: "A.B.C. Textile Limited",
    department_a: "Factories Department",
    department_b: "KSPCB",
    confidence: 0.87,
    created_at: "2024-12-15T10:30:00Z",
    age_hours: 48,
  },
  {
    case_id: "CASE-2024-0892",
    name_a: "Sri Venkateshwara Industries",
    name_b: "Venkateshwara Ind.",
    department_a: "Labour Department",
    department_b: "BESCOM",
    confidence: 0.72,
    created_at: "2024-12-14T08:15:00Z",
    age_hours: 74,
  },
  {
    case_id: "CASE-2024-0893",
    name_a: "Infosys Technologies",
    name_b: "Infosys Ltd",
    department_a: "Shop & Establishment",
    department_b: "Labour Department",
    confidence: 0.95,
    created_at: "2024-12-15T14:00:00Z",
    age_hours: 12,
  },
  {
    case_id: "CASE-2024-0894",
    name_a: "Karnataka Power Corp",
    name_b: "KPC Power Corporation",
    department_a: "Factories Department",
    department_b: "KSPCB",
    confidence: 0.68,
    created_at: "2024-12-13T09:00:00Z",
    age_hours: 120,
  },
  {
    case_id: "CASE-2024-0895",
    name_a: "Mysore Paints & Varnish",
    name_b: "Mysore Paints and Varnish Ltd",
    department_a: "KSPCB",
    department_b: "Factories Department",
    confidence: 0.91,
    created_at: "2024-12-15T16:45:00Z",
    age_hours: 6,
  },
];

export const MOCK_QUEUE: QueueResponse = {
  items: MOCK_QUEUE_ITEMS,
  total: MOCK_QUEUE_ITEMS.length,
  has_stale: true,
  stale_count: 1,
};

// ─── Review Case Detail ─────────────────────────────────────────────
export const MOCK_REVIEW_CASES: Record<string, ReviewCase> = {
  "CASE-2024-0891": {
    case_id: "CASE-2024-0891",
    confidence: 0.87,
    record_a: {
      name_raw: "ABC Textiles Pvt Ltd",
      name_normalised: "abc textiles",
      address: "No. 42, Industrial Area, Peenya, Bangalore",
      pin: "560058",
      pan: "AABCA1234L",
      gstin: "29AABCA1234L1ZA",
      phone: "080-23456789",
      department: "Factories Department",
    },
    record_b: {
      name_raw: "A.B.C. Textile Limited",
      name_normalised: "abc textile",
      address: "42, Peenya Industrial Estate, Bengaluru",
      pin: "560058",
      pan: "AABCA1234L",
      gstin: "29AABCA1234L1ZA",
      phone: "080-23456780",
      department: "KSPCB",
    },
    shap_values: [
      { feature: "name_jaro_winkler", value: 0.42 },
      { feature: "pan_exact_match", value: 0.31 },
      { feature: "gstin_match", value: 0.28 },
      { feature: "pin_match", value: 0.15 },
      { feature: "address_cosine", value: 0.12 },
      { feature: "phone_prefix_match", value: 0.08 },
      { feature: "metaphone_match", value: 0.06 },
    ],
    explanation:
      "High-confidence match driven by exact PAN and GSTIN agreement. Name similarity (Jaro-Winkler = 0.94) and same PIN code further support the merge. Minor phone number discrepancy (last digit) is consistent with different department registrations.",
    age_hours: 48,
    created_at: "2024-12-15T10:30:00Z",
  },
  "CASE-2024-0892": {
    case_id: "CASE-2024-0892",
    confidence: 0.72,
    record_a: {
      name_raw: "Sri Venkateshwara Industries",
      name_normalised: "venkateshwara industries",
      address: "Plot 15, Bommasandra Industrial Area",
      pin: "560099",
      pan: "AABCV5678K",
      gstin: "",
      phone: "080-29876543",
      department: "Labour Department",
    },
    record_b: {
      name_raw: "Venkateshwara Ind.",
      name_normalised: "venkateshwara ind",
      address: "Bommasandra, Electronic City Post",
      pin: "560100",
      pan: "",
      gstin: "29AABCV5678K2ZB",
      phone: "080-29876500",
      department: "BESCOM",
    },
    shap_values: [
      { feature: "name_jaro_winkler", value: 0.35 },
      { feature: "address_cosine", value: 0.18 },
      { feature: "phone_prefix_match", value: 0.12 },
      { feature: "pin_match", value: -0.08 },
      { feature: "gstin_match", value: -0.05 },
      { feature: "pan_exact_match", value: 0.04 },
    ],
    explanation:
      "Moderate-confidence match. Name similarity is strong but PIN codes differ by 1 digit (560099 vs 560100, adjacent areas). PAN partially confirms via GSTIN encoding. Recommend manual review.",
    age_hours: 74,
    created_at: "2024-12-14T08:15:00Z",
  },
};

// ─── UBID Detail (Analytics) ────────────────────────────────────────
export const MOCK_UBID_DETAIL: Record<string, UbidDetail> = {
  "UBID-KA-2024-00142": {
    ubid: "UBID-KA-2024-00142",
    anchor_type: "PAN",
    status: "active",
    confidence: 0.94,
    departments: ["factories", "labour", "kspcb"],
    linked_records: [
      { department: "Factories", local_id: "REG/FAC/2019/4532", name: "ABC Textiles Pvt Ltd" },
      { department: "Labour", local_id: "LAB/2020/1187", name: "ABC Textiles Private Ltd" },
      { department: "KSPCB", local_id: "KSPCB/KA/2019/892", name: "ABC Textile Ltd" },
    ],
    classification: {
      status: "active",
      confidence: 0.91,
      shap_values: {
        event_count_12m: 0.38,
        days_since_last_event: -0.22,
        dept_coverage_ratio: 0.18,
        inspection_regularity: 0.15,
        compliance_renewal_rate: 0.12,
        seasonal_variance: -0.05,
        event_type_diversity: 0.08,
        cross_dept_activity: 0.06,
        registration_age_years: 0.03,
      },
    },
  },
  "UBID-KA-2024-00287": {
    ubid: "UBID-KA-2024-00287",
    anchor_type: "GSTIN",
    status: "active",
    confidence: 0.91,
    departments: ["factories", "kspcb"],
    linked_records: [
      { department: "Factories", local_id: "REG/FAC/2020/7891", name: "Bangalore Steel Works" },
      { department: "KSPCB", local_id: "KSPCB/KA/2020/445", name: "Bangalore Steel Works Pvt Ltd" },
    ],
    classification: {
      status: "active",
      confidence: 0.88,
      shap_values: {
        event_count_12m: 0.29,
        days_since_last_event: -0.15,
        dept_coverage_ratio: 0.22,
        inspection_regularity: 0.11,
        compliance_renewal_rate: 0.19,
      },
    },
  },
  "UBID-KA-2024-00531": {
    ubid: "UBID-KA-2024-00531",
    anchor_type: "phone",
    status: "dormant",
    confidence: 0.87,
    departments: ["shop_est", "labour"],
    linked_records: [
      { department: "Shop & Establishment", local_id: "S&E/BLR/2019/334", name: "Sri Lakshmi Enterprises" },
      { department: "Labour", local_id: "LAB/2019/2456", name: "Sree Lakshmi Enterprises" },
    ],
    classification: {
      status: "dormant",
      confidence: 0.85,
      shap_values: {
        event_count_12m: -0.35,
        days_since_last_event: 0.42,
        dept_coverage_ratio: -0.12,
        inspection_regularity: -0.28,
        compliance_renewal_rate: -0.18,
      },
    },
  },
};

// ─── Activity Events (Analytics) ────────────────────────────────────
export const MOCK_EVENTS: Record<string, ActivityEvent[]> = {
  "UBID-KA-2024-00142": [
    { event_id: "EVT-001", department: "Factories", event_type: "inspection", event_ts: "2024-11-20T09:30:00Z", local_id: "REG/FAC/2019/4532", payload: { inspector: "K. Ramesh", result: "compliant" } },
    { event_id: "EVT-002", department: "KSPCB", event_type: "emission_test", event_ts: "2024-10-15T11:00:00Z", local_id: "KSPCB/KA/2019/892", payload: { result: "within_limits", pm25: 42 } },
    { event_id: "EVT-003", department: "Labour", event_type: "wage_audit", event_ts: "2024-09-08T14:00:00Z", local_id: "LAB/2020/1187", payload: { workers: 156, compliant: true } },
    { event_id: "EVT-004", department: "Factories", event_type: "license_renewal", event_ts: "2024-07-01T10:00:00Z", local_id: "REG/FAC/2019/4532", payload: { valid_until: "2025-06-30" } },
    { event_id: "EVT-005", department: "KSPCB", event_type: "consent_renewal", event_ts: "2024-05-12T09:00:00Z", local_id: "KSPCB/KA/2019/892", payload: { type: "consent_to_operate" } },
    { event_id: "EVT-006", department: "Labour", event_type: "registration_update", event_ts: "2024-03-22T16:00:00Z", local_id: "LAB/2020/1187", payload: { change: "address_update" } },
    { event_id: "EVT-007", department: "Factories", event_type: "safety_audit", event_ts: "2024-01-18T10:30:00Z", local_id: "REG/FAC/2019/4532", payload: { score: 87, grade: "A" } },
    { event_id: "EVT-008", department: "KSPCB", event_type: "inspection", event_ts: "2023-11-05T14:00:00Z", local_id: "KSPCB/KA/2019/892", payload: { result: "minor_violations" } },
  ],
  "UBID-KA-2024-00287": [
    { event_id: "EVT-010", department: "Factories", event_type: "inspection", event_ts: "2024-12-01T10:00:00Z", local_id: "REG/FAC/2020/7891", payload: { result: "compliant" } },
    { event_id: "EVT-011", department: "KSPCB", event_type: "emission_test", event_ts: "2024-10-20T11:30:00Z", local_id: "KSPCB/KA/2020/445", payload: { result: "within_limits" } },
    { event_id: "EVT-012", department: "Factories", event_type: "license_renewal", event_ts: "2024-08-15T09:00:00Z", local_id: "REG/FAC/2020/7891", payload: { valid_until: "2025-08-14" } },
  ],
  "UBID-KA-2024-00531": [
    { event_id: "EVT-020", department: "Shop & Establishment", event_type: "registration", event_ts: "2023-06-15T10:00:00Z", local_id: "S&E/BLR/2019/334", payload: { type: "initial_registration" } },
    { event_id: "EVT-021", department: "Labour", event_type: "wage_audit", event_ts: "2023-04-10T14:00:00Z", local_id: "LAB/2019/2456", payload: { workers: 12, compliant: true } },
  ],
};

// ─── Analytics Query Results ────────────────────────────────────────
export const MOCK_QUERY_RESULTS: QueryResult[] = [
  { ubid: "UBID-KA-2024-00142", name: "ABC Textiles Pvt Ltd", department: "factories", pin_code: "560058", status: "active", last_event_days: 25 },
  { ubid: "UBID-KA-2024-00287", name: "Bangalore Steel Works", department: "factories", pin_code: "560058", status: "active", last_event_days: 14 },
  { ubid: "UBID-KA-2024-00098", name: "Karnataka Chemicals & Fertilizers", department: "factories", pin_code: "560058", status: "active", last_event_days: 7 },
  { ubid: "UBID-KA-2024-00312", name: "Peenya Precision Tools", department: "factories", pin_code: "560058", status: "active", last_event_days: 45 },
  { ubid: "UBID-KA-2024-00531", name: "Sri Lakshmi Enterprises", department: "shop_est", pin_code: "560001", status: "dormant", last_event_days: 540 },
  { ubid: "UBID-KA-2024-00415", name: "Hubli Engineering Corp", department: "factories", pin_code: "580020", status: "closed", last_event_days: 890 },
  { ubid: "UBID-KA-2024-00763", name: "Mysore Silk Palace", department: "shop_est", pin_code: "570001", status: "active", last_event_days: 30 },
  { ubid: "UBID-KA-2024-00189", name: "Belgaum Auto Components", department: "factories", pin_code: "590001", status: "dormant", last_event_days: 320 },
];

// ─── Audit Log ──────────────────────────────────────────────────────
export const MOCK_AUDIT_ENTRIES: AuditEntry[] = [
  {
    id: "AUD-001",
    case_id: "CASE-2024-0880",
    record_a: "ABC Textiles Pvt Ltd",
    record_b: "A.B.C. Textile Limited",
    confidence: 0.94,
    features: { name_jaro_winkler: 0.42, pan_exact_match: 0.31, gstin_match: 0.28, pin_match: 0.15, address_cosine: 0.12 },
    resolution: "approved",
    reviewer_id: "reviewer_01",
    reviewer_note: "PAN and GSTIN exact match. Clear merge candidate.",
    resolved_at: "2024-12-14T16:30:00Z",
    ubid: "UBID-KA-2024-00142",
  },
  {
    id: "AUD-002",
    case_id: "CASE-2024-0875",
    record_a: "Infosys Technologies",
    record_b: "Infosys Ltd",
    confidence: 0.96,
    features: { name_jaro_winkler: 0.35, pan_exact_match: 0.45, gstin_match: 0.38, pin_match: 0.20, phone_prefix_match: 0.15 },
    resolution: "approved",
    reviewer_id: "auto_system",
    reviewer_note: "Auto-approved: confidence > 0.95 with PAN+GSTIN match",
    resolved_at: "2024-12-14T12:00:00Z",
    ubid: "UBID-KA-2024-00044",
  },
  {
    id: "AUD-003",
    case_id: "CASE-2024-0870",
    record_a: "Bangalore Plastics Co",
    record_b: "BPC Plastics Works",
    confidence: 0.52,
    features: { name_jaro_winkler: 0.18, address_cosine: 0.22, pin_match: 0.15, phone_prefix_match: -0.08 },
    resolution: "rejected",
    reviewer_id: "reviewer_02",
    reviewer_note: "Names are too different. Different phone numbers. Not the same entity.",
    resolved_at: "2024-12-13T15:45:00Z",
  },
  {
    id: "AUD-004",
    case_id: "CASE-2024-0865",
    record_a: "Wipro Infrastructure",
    record_b: "Wipro Infra Engineering",
    confidence: 0.78,
    features: { name_jaro_winkler: 0.32, pan_exact_match: -0.10, gstin_match: 0.25, address_cosine: 0.20, pin_match: 0.18 },
    resolution: "escalated",
    reviewer_id: "reviewer_01",
    reviewer_note: "PAN mismatch but GSTIN partially matches. Needs senior review for subsidiary vs parent entity.",
    resolved_at: "2024-12-13T11:20:00Z",
  },
  {
    id: "AUD-005",
    case_id: "CASE-2024-0860",
    record_a: "Karnataka Soaps & Detergents",
    record_b: "KS&D Ltd",
    confidence: 0.88,
    features: { name_jaro_winkler: 0.28, pan_exact_match: 0.35, gstin_match: 0.30, pin_match: 0.15, metaphone_match: 0.10 },
    resolution: "approved",
    reviewer_id: "reviewer_03",
    reviewer_note: "Government entity. PAN and GSTIN confirmed. Abbreviation pattern matches.",
    resolved_at: "2024-12-12T14:00:00Z",
    ubid: "UBID-KA-2024-00078",
  },
  {
    id: "AUD-006",
    case_id: "CASE-2024-0855",
    record_a: "Mandya Sugar Company",
    record_b: "MSC Sugars Ltd",
    confidence: 0.71,
    features: { name_jaro_winkler: 0.20, address_cosine: 0.28, pin_match: 0.18, phone_prefix_match: 0.12 },
    resolution: "deferred",
    reviewer_id: "reviewer_02",
    reviewer_note: "Need to verify with Factories Department. Records partially match but PAN unavailable.",
    resolved_at: "2024-12-12T10:30:00Z",
  },
  {
    id: "AUD-007",
    case_id: "CASE-2024-0850",
    record_a: "Shimoga Steel Rolling Mills",
    record_b: "Shimoga Steel Rolling Mills Pvt Ltd",
    confidence: 0.93,
    features: { name_jaro_winkler: 0.40, pan_exact_match: 0.32, gstin_match: 0.28, pin_match: 0.18, address_cosine: 0.15 },
    resolution: "approved",
    reviewer_id: "auto_system",
    reviewer_note: "Auto-approved: name near-identical, PAN+GSTIN confirmed",
    resolved_at: "2024-12-11T17:00:00Z",
    ubid: "UBID-KA-2024-00201",
  },
  {
    id: "AUD-008",
    case_id: "CASE-2024-0845",
    record_a: "Tumkur Cement Works",
    record_b: "TCW Industries",
    confidence: 0.45,
    features: { name_jaro_winkler: 0.12, address_cosine: 0.15, pin_match: 0.10, pan_exact_match: -0.15 },
    resolution: "rejected",
    reviewer_id: "reviewer_01",
    reviewer_note: "Different PAN, low name similarity. Likely different entities in same industrial area.",
    resolved_at: "2024-12-11T09:15:00Z",
  },
  {
    id: "AUD-009",
    case_id: "CASE-2024-0840",
    record_a: "Raichur Thermal Power Station",
    record_b: "RTPS KPCL",
    confidence: 0.85,
    features: { name_jaro_winkler: 0.15, gstin_match: 0.38, pin_match: 0.22, address_cosine: 0.25, phone_prefix_match: 0.10 },
    resolution: "approved",
    reviewer_id: "reviewer_03",
    reviewer_note: "Government power station. GSTIN match. RTPS is the well-known abbreviation.",
    resolved_at: "2024-12-10T13:45:00Z",
    ubid: "UBID-KA-2024-00055",
  },
  {
    id: "AUD-010",
    case_id: "CASE-2024-0835",
    record_a: "HAL Aerospace",
    record_b: "Hindustan Aeronautics Ltd",
    confidence: 0.97,
    features: { name_jaro_winkler: 0.22, pan_exact_match: 0.48, gstin_match: 0.42, pin_match: 0.20, phone_prefix_match: 0.18 },
    resolution: "approved",
    reviewer_id: "auto_system",
    reviewer_note: "Auto-approved: PAN+GSTIN exact match, confidence 0.97",
    resolved_at: "2024-12-10T08:00:00Z",
    ubid: "UBID-KA-2024-00012",
  },
  {
    id: "AUD-011",
    case_id: "CASE-2024-0830",
    record_a: "Davangere Cotton Mills",
    record_b: "DCM Textiles",
    confidence: 0.62,
    features: { name_jaro_winkler: 0.15, address_cosine: 0.20, pin_match: 0.15, pan_exact_match: 0.08 },
    resolution: "escalated",
    reviewer_id: "reviewer_02",
    reviewer_note: "Possible subsidiary. Similar address but names diverge significantly. Manager review needed.",
    resolved_at: "2024-12-09T16:00:00Z",
  },
  {
    id: "AUD-012",
    case_id: "CASE-2024-0825",
    record_a: "BEML Ltd",
    record_b: "Bharat Earth Movers Limited",
    confidence: 0.98,
    features: { name_jaro_winkler: 0.18, pan_exact_match: 0.50, gstin_match: 0.45, pin_match: 0.22, address_cosine: 0.20 },
    resolution: "approved",
    reviewer_id: "auto_system",
    reviewer_note: "Auto-approved: confidence 0.98, government PSU, all identifiers match",
    resolved_at: "2024-12-09T10:30:00Z",
    ubid: "UBID-KA-2024-00008",
  },
];
